# Self-contained multi-arch build for the surminus fork.
# Cross-compiles the Go binary so we avoid slow QEMU emulation: the build
# stage always runs on the native build platform and targets TARGETARCH.
ARG GO_VERSION=1.26

FROM --platform=$BUILDPLATFORM golang:${GO_VERSION} AS build
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG TARGETOS
ARG TARGETARCH
ARG VERSION=dev
ARG REVISION=unknown
ARG BRANCH=unknown

RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build \
      -ldflags "\
        -X github.com/prometheus/common/version.Version=${VERSION} \
        -X github.com/prometheus/common/version.Revision=${REVISION} \
        -X github.com/prometheus/common/version.Branch=${BRANCH} \
        -X github.com/prometheus/common/version.BuildUser=docker@github-actions \
        -X github.com/prometheus/common/version.BuildDate=unknown" \
      -o /bin/yace ./cmd/yace

FROM gcr.io/distroless/static-debian12:nonroot
LABEL org.opencontainers.image.source="https://github.com/surminus/yet-another-cloudwatch-exporter"

COPY --from=build /bin/yace /bin/yace
COPY examples/ec2.yml /etc/yace/config.yml

EXPOSE     5000
USER       nonroot
ENTRYPOINT [ "/bin/yace" ]
CMD        [ "--config.file=/etc/yace/config.yml" ]
